- hosts: production
  become: true
  tasks:
  - name: "Update packages"
    ansible.builtin.dnf:
      update_cache: yes
      name: "*"
      state: latest
  - name: "Install net-tools"
    ansible.builtin.dnf:
      name: net-tools
      state: latest
